version: '3'

services:
  webserver:
    image: 'cloudwaysdev/ansiblestretch'    
    volumes:
      - '~/container-ssh-keys/authorized_keys:/root/.ssh/authorized_keys'
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.22
  appserver:
    image: 'cloudwaysdev/ansiblestretch'   
    volumes:
      - '~/container-ssh-keys/authorized_keys:/root/.ssh/authorized_keys'
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.23

  dbserver:
    image: 'cloudwaysdev/ansiblestretch'  
    volumes:
      - '~/container-ssh-keys/authorized_keys:/root/.ssh/authorized_keys'
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.24

networks:
  xenial_nw:
    external:
      name: ansible_nw