version: '3'

services:
  webserver:
    image: 'cloudwaysdev/ansiblestretch'
    environment:
      - SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"
    volumes:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    # volumes:
    #   - './ssh_data/:/root/.ssh/'
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.22
  appserver:
    image: 'cloudwaysdev/ansiblestretch'
    environment:
      - SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"
    volumes:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    # volumes:
    #   - './ssh_data/:/root/.ssh/'
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.23

  dbserver:
    image: 'cloudwaysdev/ansiblestretch'
    environment:
      - SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"
    volumes:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    # volumes:
    #   - './ssh_data/:/root/.ssh/'
    networks:
      xenial_nw:
        ipv4_address: 172.5.0.24

networks:
  xenial_nw:
    external:
      name: ansible_nw